import { Injectable, Logger } from '@nestjs/common';
import { DatabaseService } from '../../services/database.service';
import { SpotifyService } from '../../services/spotify.service';
import { NLPRecommendationModel, NLPRecommendationRequest } from '../models/nlp-recommendation.model';
import { Track } from '@prisma/client';

/**
 * Service for handling natural language-based music recommendations
 */
@Injectable()
export class NLPRecommendationService {
  private nlpModel: NLPRecommendationModel;
  private readonly logger = new Logger(NLPRecommendationService.name);

  constructor(
    private database: DatabaseService,
    private spotify: SpotifyService
  ) {
    this.nlpModel = new NLPRecommendationModel();
  }

  /**
   * Get music recommendations based on a natural language query
   */
  async getRecommendationsFromText(request: NLPRecommendationRequest): Promise<Track[]> {
    this.logger.log(`Processing NLP recommendation request: "${request.query}"`);
    
    // Get all tracks with audio features
    const tracks = await this.database.track.findMany({
      include: {
        audioFeatures: true
      }
    });
    
    this.logger.log(`Found ${tracks.length} tracks to analyze for NLP recommendations`);
    
    // Use the NLP model to get recommendations
    const recommendations = await this.nlpModel.getRecommendationsFromQuery(request, tracks);
    
    this.logger.log(`Generated ${recommendations.length} recommendations based on NLP query`);
    
    return recommendations;
  }

  /**
   * Create a playlist from a natural language query
   */
  async createPlaylistFromText(
    userId: string,
    query: string,
    playlistName?: string
  ): Promise<{ playlistId: string; tracks: Track[] }> {
    // Get recommendations based on the query
    const recommendations = await this.getRecommendationsFromText({
      query,
      userId,
      limit: 20
    });
    
    if (recommendations.length === 0) {
      throw new Error('Could not generate recommendations from the text query');
    }
    
    // Get user with Spotify token
    const user = await this.database.user.findUnique({
      where: { id: userId }
    });
    
    if (!user?.spotifyAccessToken) {
      throw new Error('User not found or missing Spotify access token');
    }
    
    // Create a name for the playlist if not provided
    const name = playlistName || `Playlist based on: ${query}`;
    
    // Create playlist on Spotify
    const playlist = await this.spotify.createPlaylist(
      user.spotifyAccessToken,
      user.spotifyId,
      name,
      `Generated by Audotics based on the query: "${query}"`
    );
    
    // Add tracks to the playlist
    const trackUris = recommendations.map(track => `spotify:track:${track.spotifyId}`);
    await this.spotify.addTracksToPlaylist(
      user.spotifyAccessToken,
      playlist.id,
      trackUris
    );
    
    this.logger.log(`Created playlist "${name}" with ${recommendations.length} tracks`);
    
    return {
      playlistId: playlist.id,
      tracks: recommendations
    };
  }
} 